# Generated by Django 4.1 on 2022-08-08 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_prompt_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('challenge', models.CharField(max_length=2250)),
                ('action', models.CharField(max_length=2250)),
                ('response', models.CharField(max_length=2250)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.prompt')),
            ],
        ),
    ]
