# Generated by Django 4.1 on 2022-08-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_used_alter_car_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='used',
            name='asked',
        ),
    ]
