# Generated by Django 4.1 on 2022-08-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_qualities_delete_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='qualities',
            field=models.ManyToManyField(to='main_app.qualities'),
        ),
    ]
