# Generated by Django 4.1 on 2022-08-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_prompt_qualities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='qualities',
        ),
        migrations.DeleteModel(
            name='Qualities',
        ),
    ]
