# Generated by Django 4.1 on 2022-08-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_prompt_qualities_delete_qualities'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='pics',
            field=models.CharField(choices=[('static/images/alien2.png', 'alien'), ('static/images/stars.png', 'stars'), ('static/images/day-and-night.png', 'day/night'), ('static/images/galaxy.png', 'galaxy'), ('static/images/abduction.png', 'ufo'), ('static/images/spacedog.png', 'space dog'), ('static/images/meteor.png', 'meteor')], default='static/images/alien2.png', max_length=255),
        ),
    ]
