# Generated by Django 4.1 on 2022-08-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_prompt_pics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='pics',
        ),
    ]
