# Generated by Django 4.1 on 2022-08-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_prompt_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='question',
            field=models.TextField(max_length=250),
        ),
    ]
